CREATE TABLE users (
    IDUSER INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    STATUS BOOLEAN NOT NULL,
    GRUPO VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    REPETIRSENHA VARCHAR(255) NOT NULL
);
