CREATE TABLE Produtos (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL
);